## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
array = np.random.randint(1, 10, size=(10))
print(array)

array[(array>3) & (array<8)] *= -1
print(array)

[3 5 7 4 9 3 6 6 7 3]
[ 3 -5 -7 -4  9  3 -6 -6 -7  3]


**2.** Заменить максимальный элемент случайного массива на 0

In [ ]:
array = np.random.randint(1, 10, size=(10))
print(array)

array[array == np.max(array)] = 0
print(array)

[7 6 6 1 6 2 8 6 8 2]
[7 6 6 1 6 2 0 6 0 2]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [ ]:
array = np.random.randint(1, 10, size=(3, 3))
print(array)

kron_array = np.kron(array, array)
print(kron_array)

[[8 7 7]
 [6 8 3]
 [4 3 8]]
[[64 56 56 56 49 49 56 49 49]
 [48 64 24 42 56 21 42 56 21]
 [32 24 64 28 21 56 28 21 56]
 [48 42 42 64 56 56 24 21 21]
 [36 48 18 48 64 24 18 24  9]
 [24 18 48 32 24 64 12  9 24]
 [32 28 28 24 21 21 64 56 56]
 [24 32 12 18 24  9 48 64 24]
 [16 12 32 12  9 24 32 24 64]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [ ]:
arrayA = np.random.randint(1, 10, size=(8, 3))
arrayB = np.random.randint(1, 10, size=(2, 2))
print(arrayA, '\n\n', arrayB)

rowIndexes = []

arrayB_elements = arrayB.flatten()
print(arrayB_elements)

for index, row in enumerate(arrayA):
  if np.all(np.isin(arrayB_elements, row)):
    rowIndexes.append(index)

arrayA_rows = arrayA[rowIndexes]
print(arrayA_rows)

[[6 1 6]
 [6 6 4]
 [9 1 9]
 [5 4 1]
 [5 8 8]
 [8 1 2]
 [5 9 8]
 [8 6 9]] 

 [[1 6]
 [3 3]]
[1 6 3 3]
[]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [ ]:
array = np.random.randint(1, 5, size=(10, 3))
print(array)

rowIndexes = []

for index, row in enumerate(array):
  if np.all(np.diff(row)==0):
    rowIndexes.append(index)

print(np.delete(array, rowIndexes, axis=0))

[[1 4 1]
 [3 3 3]
 [2 4 2]
 [2 2 3]
 [3 1 2]
 [3 4 3]
 [3 1 4]
 [2 1 1]
 [4 4 2]
 [1 1 4]]
[[1 4 1]
 [2 4 2]
 [2 2 3]
 [3 1 2]
 [3 4 3]
 [3 1 4]
 [2 1 1]
 [4 4 2]
 [1 1 4]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [ ]:
array = np.random.randint(1, 5, size=(10, 3))
print(array)

unique_array = np.unique(array, axis=0)
print(unique_array)

[[1 1 4]
 [2 3 1]
 [1 2 3]
 [1 4 2]
 [1 1 4]
 [2 1 4]
 [2 2 1]
 [4 2 1]
 [1 3 2]
 [4 4 3]]
[[1 1 4]
 [1 2 3]
 [1 3 2]
 [1 4 2]
 [2 1 4]
 [2 2 1]
 [2 3 1]
 [4 2 1]
 [4 4 3]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]])

diagonalX = np.diag(X)
result = np.prod(diagonalX[diagonalX != 0])
print(result)

#############

X_list = [[1, 0, 1],
          [2, 0, 2],
          [3, 0, 3],
          [4, 4, 4]]

diagonal_length = min(len(X_list), len(X_list[0])) if len(X_list) != 0 else 0
non_zero_elements = False
result = 1


for i in range(diagonal_length):
  if X_list[i][i] != 0:
    result *= X_list[i][i]
    non_zero_elements = True
if non_zero_elements == False:
  result = 0

print(result)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

result = np.array_equal(np.sort(x), np.sort(y))
print(result)

#########

x_list = [1, 2, 2, 4]
y_list = [4, 2, 1, 2]

result = sorted(x_list) == sorted(y_list)
print(result)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

zero_indexes = np.where(x == 0)[0]
past_zeroes_indexes = zero_indexes + 1
x_past_zeroes = x[past_zeroes_indexes[past_zeroes_indexes < len(x)]]
max_value_past_zero = np.max(x_past_zeroes)
print(max_value_past_zero)

#########

x_list = [6, 2, 0, 3, 0, 0, 5, 7, 0]

current_max = 0

for i in range(len(x_list)):
  if i>0 and x_list[i-1] == 0 and x_list[i] > current_max:
    current_max = x_list[i]

print(current_max)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
edges = np.where(x[1:] != x[:-1])[0]
edges = np.concatenate((edges, [len(x) - 1]))
values = x[edges]
counts = np.diff(np.concatenate(([-1], edges)))
result = [values, counts]
print(result)

#######

x_list = [2, 2, 2, 3, 3, 3, 5]
values = []
counts = []
for i in range(len(x_list)):
  if i==len(x_list)-1 or (i<len(x_list)-1 and x_list[i] != x_list[i+1]):
    values.append(x_list[i])
    counts.append(i+1 if len(counts)==0 else (i + 1 - sum(counts)))

result = [values, counts]
print(result)

[array([2, 3, 5]), array([3, 3, 1])]
[[2, 3, 5], [3, 3, 1]]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [31]:
from scipy.spatial.distance import cdist
import time

X = np.random.rand(1000, 200)
Y = np.random.rand(2000, 200)

def euclidean_distance(X, Y):
    x2 = np.sum(X**2, axis=1)[:, np.newaxis]
    y2 = np.sum(Y**2, axis=1)[np.newaxis, :]
    xy = np.dot(X, Y.T)
    sq_dists = np.maximum(x2 - 2 * xy + y2, 0)
    return np.sqrt(sq_dists)

start = time.time()
distance_numpy = euclidean_distance(X, Y)
result_time_numpy = time.time() - start
print(f'Numpy time: {result_time_numpy}')

start = time.time()
dist_scipy = cdist(X, Y, metric='euclidean')
result_time_scipy = time.time() - start
print(f"SciPy time: {result_time_scipy}")

Numpy time: 0.05134439468383789
SciPy time: 0.2615673542022705


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
average_calories = np.average(calorie_stats)
average_calories

np.float64(106.88311688311688)

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
median_calories = np.median(calorie_stats)
median_calories

np.float64(110.0)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
for i in range(1, 100):
  procentile_value = np.percentile(calorie_stats, i)
  if procentile_value > 60:
    nth_percentile = procentile_value
    break

nth_percentile

np.float64(70.0)

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:
more_calories = np.mean(calorie_stats > 60) * 100

more_calories

np.float64(96.1038961038961)

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
calorie_std = np.std(calorie_stats)
calorie_std

np.float64(0.19350213539936806)

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
'''Как по мне, для широкой аудитории будет важным результат подсчетов доли хлопьев
в которых калорий больше, чтоб показать насколько полезнее хлопья CrunchieMunchies'''